version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: usine
      POSTGRES_USER: usine
      POSTGRES_PASSWORD: usine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DB_URL: postgresql+psycopg2://usine:usine@db:5432/usine
      JWT_SECRET: change-me
      FLASK_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  pgdata:
